services:
  backend:
    build: 
      context: ./epiclevelsoft
    container_name: backend
    volumes:
      - ./epiclevelsoft:/home/app/src
    working_dir: /home/app/src
    command: 
      - ./mvnw
      - quarkus:dev
    environment:
      - QUARKUS_DATASOURCE_PASSWORD=level
      - QUARKUS_DATASOURCE_USERNAME=root
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:mariadb://epicdb:3306/epiclevel
      - QUARKUS_HTTP_HOST=0.0.0.0
    ports:
      - 8080:8080
  database:
    image: mariadb:latest
    container_name: epicdb
    environment:
      - MARIADB_DATABASE=epiclevel
      - MARIADB_ROOT_PASSWORD=level
    # ports:
    #   - 3306:3306
  frontend:
    build:
      context: ./epicFront
    container_name: frontend
    volumes:
      - ./epicFront:/home/app/src
    working_dir: /home/app/src
    command: ["/bin/sh", "-c", "rm -f /tmp/nitro/worker-*.sock; if [ -d node_modules]; then npm i && npm run dev; else npm run dev; fi"]
    ports:
      - 3000:3000
    